//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class escritoPor
    {
        public int Id { get; set; }
        public int Id_Autor { get; set; }
        public int Id_Libro { get; set; }
    
        public virtual Autore Autore { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
